tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
brew "readline"
brew "asdf"
brew "bat"
brew "bottom"
brew "sqlite"
brew "xz"
brew "colima"
brew "docker"
brew "docker-compose"
brew "exa"
brew "fd"
brew "fzf"
brew "gh"
brew "git"
brew "gnupg"
brew "lua-language-server"
brew "luajit", args: ["HEAD"]
brew "mas"
brew "neovim", args: ["HEAD"]
brew "pure"
brew "ripgrep"
brew "stow"
brew "tmux"
brew "unar"
brew "wget"
brew "zsh-autosuggestions"
cask "alacritty"
cask "font-jetbrains-mono-nerd-font"
cask "rectangle"
cask "the-unarchiver"
mas "AdGuard for Safari", id: 1440147259
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Telegram", id: 747648890
mas "WhatsApp", id: 1147396723
