require("keymaps")
require("sets")
require("netrw")
require("plugins")
require("configs.treesitter")
require("configs.telescope")
require("configs.lsp")
require("configs.cmp")
require("configs.colors")
-- require("configs.lualine")
require("configs.comment")
require("configs.toggleterm")
require("configs.snippets")
--require("configs.dap")
