require('keymaps')
require('sets')
require('netrw')
require('plugins')
require('configs.treesitter')
require('configs.telescope')
require('configs.lsp')
require('configs.cmp')
require('configs.colors')
require('configs.lualine')
require('configs.dap')
require('configs.snippets')
require('configs.comment')

require('neoscroll').setup()
