set -ga terminal-overrides ",xterm-256color:Tc"
set-option -g default-terminal "screen-256color"
set -g default-terminal "screen-256color"

# prefix
unbind C-b
set -g prefix C-Space

# source config
unbind r
bind r source-file ~/.tmux.conf \; display "Reloaded ~/tmux.conf"

# mouse
set -g mouse on

# vim
setw -g mode-keys vi

set-option -sg escape-time 10
set-option -g focus-events on
set -g renumber-windows on

# Undercurl
set -g default-terminal "${TERM}"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0

set -g status-right '#[fg=colour233,bold] %d/%m #[fg=colour233,bold] %H:%M:%S '

# setw -g window-status-current-format ' #I#[fg=colour250]:#[fg=colour255]#W#[fg=colour50]#F '
# setw -g window-status-format ' #I#[fg=colour237]:#[fg=colour250]#W#[fg=colour244]#F '

set-option -g history-limit 5000
